# 🔢 One Hot Encoding (OHE)

When working in Machine Learning, models only understand **numbers**.
But real datasets contain categories like:

| Color |
|-------|
| Red |
| Blue |
| Green |

A model **cannot** directly understand `"Red"` or `"Blue"`.
So we need a way to **convert categories into numbers**.

One of the safest and most common techniques is:

> ## ✅ One Hot Encoding

---

## 💡 Core Idea

Instead of giving categories **fake numeric meaning** like:

| Color | Encoded |
|-------|---------|
| Red | 1 |
| Blue | 2 |
| Green | 3 |

*(which wrongly suggests Green > Blue > Red)*

we **create separate columns** for every category.

---

## 📌 Basic Example

Suppose:

| Color |
|-------|
| Red |
| Blue |
| Green |

After One Hot Encoding:

| Red | Blue | Green |
|-----|------|-------|
| 1 | 0 | 0 |
| 0 | 1 | 0 |
| 0 | 0 | 1 |

Each row has:
- `1` → category **exists**
- `0` → category **absent**

That's why it's called **"One Hot"** — only **ONE** column becomes **HOT (1)**, others stay **cold (0)**.

---

## 🏠 Real Life Intuition

Imagine a room with **3 switches**:
- 🔴 Red switch
- 🔵 Blue switch
- 🟢 Green switch

If `color = Red`:

| Red | Blue | Green |
|-----|------|-------|
| ON | OFF | OFF |

If `color = Blue`:

| Red | Blue | Green |
|-----|------|-------|
| OFF | ON | OFF |

Exactly the same idea.

---

## ❓ WHY Not Just Label Encoding?

Suppose:

| City | Label Encoded |
|------|--------------|
| Lahore | 1 |
| Karachi | 2 |
| Islamabad | 3 |

The model may think:
- **Islamabad > Karachi > Lahore**
- or some **numerical distance** exists

But cities have **NO mathematical order**.

> ✅ So One Hot Encoding **avoids this issue**.

---

## 🧪 Dry Run — Step By Step

Suppose dataset:

| Fruit |
|-------|
| Apple |
| Banana |
| Mango |
| Apple |

### Step 1: Find Unique Categories

Unique fruits:
- Apple
- Banana
- Mango

### Step 2: Create Columns

Create **one column per category**:

| Apple | Banana | Mango |
|-------|--------|-------|

### Step 3: Fill Values

**Row 1 → Apple**

| Apple | Banana | Mango |
|-------|--------|-------|
| 1 | 0 | 0 |

**Row 2 → Banana**

| Apple | Banana | Mango |
|-------|--------|-------|
| 0 | 1 | 0 |

**Row 3 → Mango**

| Apple | Banana | Mango |
|-------|--------|-------|
| 0 | 0 | 1 |

**Row 4 → Apple**

| Apple | Banana | Mango |
|-------|--------|-------|
| 1 | 0 | 0 |

### ✅ Final Encoded Dataset

| Apple | Banana | Mango |
|-------|--------|-------|
| 1 | 0 | 0 |
| 0 | 1 | 0 |
| 0 | 0 | 1 |
| 1 | 0 | 0 |

---

## 📐 Mathematical Intuition

One Hot Encoding represents categories as **vectors**:

Apple  = [1, 0, 0]
Banana = [0, 1, 0]
Mango  = [0, 0, 1]

Notice:
- Categories become **independent**
- **No ordering** exists
- **Equal distance** maintained

> This helps ML models treat all categories **fairly**.

---

## Alphabtical Order in Cols:

When creating dummy columns:

        Blue
        Green
        Red

> They are sorted alphabetically:
    
    Blue → Green → Red

## ✅ When To Use One Hot Encoding

### 1. Nominal Categories
Meaning: **NO order/ranking exists**

Examples:
- Colors
- Cities
- Animal types
- Departments

✅ **Good for OHE.**

### 2. Small Number of Categories

| Feature | Categories |
|---------|-----------|
| Gender | 2 |
| Color | 5 |

✅ **Perfect.**

---

## ❌ When NOT To Use One Hot Encoding

### 1. Too Many Unique Categories

Example:

| UserID |
|--------|
| U001 |
| U002 |
| ... 100000 |

OHE would create **100,000 columns** — very bad!

This causes:
- 🔴 Huge memory usage
- 🔴 Slow training
- 🔴 Sparse data

This is called:
> ### 💥 Curse of Dimensionality

### 2. Ordered Categories

Example:

| Education |
|-----------|
| Primary |
| Secondary |
| University |

There **IS** an order. Using OHE **loses** that relationship.

> ✅ **Better:** Use **Ordinal Encoding** instead.

---

## 👍 Advantages

| # | Advantage |
|---|-----------|
| 1 | **Removes Fake Ordering** — very important |
| 2 | **Easy to Understand** — simple binary logic |
| 3 | **Works great** for Linear Regression, Logistic Regression, Neural Networks |
| 4 | **Safer** than Label Encoding for non-ordered data |

---

## 👎 Disadvantages

| # | Disadvantage |
|---|-------------|
| 1 | **Too Many Columns** — 1000 cities = 1000 columns |
| 2 | **Sparse Matrix** — most values become `0`, wastes memory |
| 3 | **Slower Training** — more columns = more computations |

---

## Two Ways to Do OHE

| Method | Library | Best For |
|--------|---------|----------|
| **Method 1** | `pd.get_dummies()` | Quick EDA, simple projects |
| **Method 2** | `sklearn.preprocessing.OneHotEncoder` | Production pipelines, consistent train/test |

---

## Method 1: Pandas `pd.get_dummies()`

```python
import pandas as pd

# Sample data
df = pd.DataFrame({
    'Color': ['Red', 'Blue', 'Green', 'Blue', 'Red']
})

# One-hot encode the 'Color' column
df_encoded = pd.get_dummies(df, columns=['Color'])

```

## Method 2: Sklearn `OneHotEncoder`

```python

from sklearn.preprocessing import OneHotEncoder
import pandas as pd
import numpy as np

# Sample data (must be 2D array)
df = pd.DataFrame({
    'Color': ['Red', 'Blue', 'Green', 'Blue', 'Red']
})

# Create encoder
encoder = OneHotEncoder() # creates a blank encoder object 

# Fit and transform
encoded_array = encoder.fit_transform(df[['Color']])

"""
FIT: Learns all unique categories from your data (like making a list of all colors)

TRANSFORM: Converts each row into 0s and 1s based on those categories


##
Fit
##

Input data: ['Red', 'Blue', 'Green', 'Blue', 'Red']

Encoder asks: "What unique colors do I see?"
Answer: ['Blue', 'Green', 'Red']

Encoder stores: categories_ = ['Blue', 'Green', 'Red']


### 
Transform
###

For each value, create a row of 3 columns:

'Red'  → [0, 0, 1]  (Blue? No. Green? No. Red? Yes)
'Blue' → [1, 0, 0]  (Blue? Yes. Green? No. Red? No)
'Green'→ [0, 1, 0]  (Blue? No. Green? Yes. Red? No)


"""

# Convert to DataFrame for viewing
df_encoded = pd.DataFrame(
    encoded_array.toarray(), # cnvrt sparce matrix into regular array we could understand ( of 0s and 1s  )
    columns=encoder.get_feature_names_out(['Color']) # Returns the column names for each encoded category in the correct order.
)


# output
   Color_Blue  Color_Green  Color_Red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         1.0          0.0        0.0
4         0.0          0.0        1.0

```

```
Step 1: Create encoder
┌─────────────────────────┐
│  encoder = OneHotEncoder()  │
│  [Empty encoder - knows nothing]  │
└─────────────────────────┘

Step 2: Learn and convert
┌─────────────────────────┐
│  encoded_array =            │
│  encoder.fit_transform(     │
│      df[['Color']]          │
│  )                          │
└─────────────────────────┘
         │
         ▼
┌─────────────────────────┐
│  Sparse Matrix           │
│  (Memory efficient)      │
│  <5x3 sparse matrix>     │
└─────────────────────────┘

Step 3: Make readable
┌─────────────────────────┐
│  encoded_array.toarray()   │
│  [Dense array of 0s and 1s] │
└─────────────────────────┘

Step 4: Get column names
┌─────────────────────────┐
│  encoder.get_feature_names_out(['Color'])  │
│  ['Color_Blue', 'Color_Green', 'Color_Red']│
└─────────────────────────┘

Step 5: Create DataFrame
┌─────────────────────────┐
│  df_encoded = pd.DataFrame(  │
│      dense_array,            │
│      columns=column_names    │
│  )                           │
└─────────────────────────┘
         │
         ▼
┌─────────────────────────┐
│  Final Result:           │
│  Color_Blue Color_Green Color_Red  │
│  0.0        0.0         1.0       │
│  1.0        0.0         0.0       │
└─────────────────────────┘

```



In [11]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
## Using pd.dummies

In [1]:
import pandas as pd

df = pd.DataFrame({
    "Color": ["Red", "Blue", "Green", "Red", "Green"]
})

print(df)

   Color
0    Red
1   Blue
2  Green
3    Red
4  Green


In [ ]:
dummies = pd.get_dummies(df)
print(dummies)

## see output it added name of OG i.e Color + Catigory = Color_Blue , Color_Green etc
## aslo they are arranged in lexographical order ist Blue as start from "B" then Grenen as "G" then Red as "R"

   Color_Blue  Color_Green  Color_Red
0       False        False       True
1        True        False      False
2       False         True      False
3       False        False       True
4       False         True      False


In [3]:
# to make it int

dummies = pd.get_dummies(df, dtype=int)
print(dummies)

   Color_Blue  Color_Green  Color_Red
0           0            0          1
1           1            0          0
2           0            1          0
3           0            0          1
4           0            1          0


In [4]:
df = pd.DataFrame({
    "City": ["Lahore", "Karachi", "Islamabad", "Lahore", "Islamabad"]
})

dummies = pd.get_dummies(df, dtype=int)
print(dummies)

   City_Islamabad  City_Karachi  City_Lahore
0               0             0            1
1               0             1            0
2               1             0            0
3               0             0            1
4               1             0            0


In [6]:
df = pd.DataFrame({
    "Color": ["Red", "Blue", "Green", "Red"],
    "Gender": ["Male", "Female", "Male", "Female"]
})

print(df)
print()
dummies = pd.get_dummies(df, dtype=int)

print(dummies)

   Color  Gender
0    Red    Male
1   Blue  Female
2  Green    Male
3    Red  Female

   Color_Blue  Color_Green  Color_Red  Gender_Female  Gender_Male
0           0            0          1              0            1
1           1            0          0              1            0
2           0            1          0              0            1
3           0            0          1              1            0


In [9]:
## without the prefix of Col name
df = pd.DataFrame({
    "Color": ["Red", "Blue", "Green"]
})

print(df)
print()

dummies = pd.get_dummies(df, prefix="",  dtype = int)

print(dummies)

   Color
0    Red
1   Blue
2  Green

   _Blue  _Green  _Red
0      0       0     1
1      1       0     0
2      0       1     0


---

# Using skleand

In [10]:
df = pd.DataFrame({
    "Color": ["Red", "Blue", "Green", "Red", "Blue"]
})

print(df)

   Color
0    Red
1   Blue
2  Green
3    Red
4   Blue


In [17]:
from sklearn.preprocessing import OneHotEncoder

# created Encoder object
encoder = OneHotEncoder()

# fit + transfrom 

encoded =  encoder.fit_transform(df[['Color']])
#fit : learn catigories
#transdorm: cnvrt to binary 

# we get a sparse matrix
print(encoded)
# convert to readable format 
print(encoded.toarray())
# check categories
print(encoder.categories_)

## Make it readle df 

encoded_df = pd.DataFrame(
    encoded.toarray(),
    columns=encoder.get_feature_names_out()
)

print()
print("Og df \n", df)

print()
print()
print(encoded_df)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 5 stored elements and shape (5, 3)>
  Coords	Values
  (0, 2)	1.0
  (1, 0)	1.0
  (2, 1)	1.0
  (3, 2)	1.0
  (4, 0)	1.0
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[array(['Blue', 'Green', 'Red'], dtype=object)]

Og df 
    Color
0    Red
1   Blue
2  Green
3    Red
4   Blue


   Color_Blue  Color_Green  Color_Red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          0.0        1.0
4         1.0          0.0        0.0


# handling Unseen Catigories 
Unseen categories are values that appear in test data (or future data) but were NOT present during training


You train a model on known data.

Then new data comes in…

👉 If a category appears that the model has NEVER seen before → that is an unseen category.

In [ ]:
from sklearn.preprocessing import OneHotEncoder

# this is data data we train our model on
train = pd.DataFrame({
    "Color": ["Red", "Blue", "Green", "Red"]
})

print(train)

   Color
0    Red
1   Blue
2  Green
3    Red


In [19]:
# make encoder object
encoder = OneHotEncoder()

# fit + transform 
encoded = encoder.fit_transform(df[["Color"]])

    # it learn: Red, Blue, Green

# Make Dtaframe 

encoded_df = pd.DataFrame(
    encoded.toarray(),
    columns = encoder.get_feature_names_out()
)

print(encoded_df)


   Color_Blue  Color_Green  Color_Red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          0.0        1.0
4         1.0          0.0        0.0


In [ ]:
## NOw new Data Arrives 

test = pd.DataFrame({
    "Color": ["Red", "Blue", "Yellow"]
})

# yellow was never seen in training 

In [ ]:
# to handle unseen catigories 
# seee fit and Tranfrom are use separatly
# We learn from training data only, and then apply the same learning to test data.

encoder = OneHotEncoder(handle_unknown="ignore")

encoder.fit(train[["Color"]])
"""
“Learn the rules from training data”

Blue  → [1,0,0]
Green → [0,1,0]
Red   → [0,0,1]
"""

encoded_test = encoder.transform(test[["Color"]]).toarray()
"""
“Apply the learned rules to new data”

So it uses the SAME mapping:

Red → [0,0,1]
Blue → [1,0,0]
Yellow → unknown → [0,0,0]
"""

print(encoded_test) # see yellow has become all zeros 

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 0.]]


---

In [ ]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

# ------------------------
# STEP 1: TRAIN DATA (model learns from this)
# ------------------------
train = pd.DataFrame({
    "Color": ["Red", "Blue", "Green", "Red"],
    "City": ["Lahore", "Karachi", "Lahore", "Islamabad"]
})

print(train)
print()

# ------------------------
# STEP 2: CREATE & FIT ENCODER ON TRAIN DATA
# ------------------------
encoder = OneHotEncoder(handle_unknown="ignore", sparse_output=False)

encoded_train = encoder.fit_transform(train)
"""
it actually is:

encoder.fit(train)      # learn categories
encoder.transform(train) # convert data
"""

encoded_train_df = pd.DataFrame(
    encoded_train,
    columns=encoder.get_feature_names_out()
)

print("TRAIN ENCODED DATA:")
print(encoded_train_df)

# ------------------------
# STEP 3: NEW TEST DATA ARRIVES LATER
# (includes unseen category: "NewCity")
# ------------------------
test = pd.DataFrame({
    "Color": ["Red", "Blue"],
    "City": ["Lahore", "NewCity"]   # unseen category here
})

# ------------------------
# STEP 4: TRANSFORM TEST DATA USING SAME ENCODER
# ------------------------
encoded_test = encoder.transform(test)

encoded_test_df = pd.DataFrame(
    encoded_test,
    columns=encoder.get_feature_names_out()
)

print("\nTEST ENCODED DATA:")
print(encoded_test_df)

## Obser carefully you wouldnt see a column for "NewCity" with all zeros b/c we make columns build from Trainig data and there "Newcity" wasn't there 
### it is all zeros but has no colms 

""""
During fit(train) it saw:

Color → Red, Blue, Green  
City  → Lahore, Karachi, Islamabad


-> so it created only:

City_Lahore
City_Karachi
City_Islamabad

👉 “NewCity” was NEVER in training
👉 So encoder has NO column for it

"""

   Color       City
0    Red     Lahore
1   Blue    Karachi
2  Green     Lahore
3    Red  Islamabad

TRAIN ENCODED DATA:
   Color_Blue  Color_Green  Color_Red  City_Islamabad  City_Karachi  \
0         0.0          0.0        1.0             0.0           0.0   
1         1.0          0.0        0.0             0.0           1.0   
2         0.0          1.0        0.0             0.0           0.0   
3         0.0          0.0        1.0             1.0           0.0   

   City_Lahore  
0          1.0  
1          0.0  
2          1.0  
3          0.0  

TEST ENCODED DATA:
   Color_Blue  Color_Green  Color_Red  City_Islamabad  City_Karachi  \
0         0.0          0.0        1.0             0.0           0.0   
1         1.0          0.0        0.0             0.0           0.0   

   City_Lahore  
0          1.0  
1          0.0  


---


In [39]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

# -----------------------------
# STEP 1: FULL DATA (like real dataset)
# -----------------------------
df = pd.DataFrame({
    "City": ["Lahore", "Karachi", "Islamabad", "Lahore", "Karachi", "Multan"],
    "Plan": ["Basic", "Premium", "Basic", "Gold", "Premium", "Basic"],
    "Device": ["Mobile", "Laptop", "Mobile", "Tablet", "Mobile", "Watch"]
})

print("FULL DATA:\n", df)

# -----------------------------
# STEP 2: SPLIT INTO TRAIN / TEST
# (simulate real ML scenario)
# -----------------------------
train = df.iloc[:4]   # first 4 rows
test = pd.DataFrame({
    "City": ["Lahore", "NewCity"],   # unseen category
    "Plan": ["Basic", "VIP"],        # unseen category
    "Device": ["Mobile", "VR"]       # unseen category
})

print("\nTRAIN DATA:\n", train)
print("\nTEST DATA:\n", test)

# -----------------------------
# STEP 3: ONE HOT ENCODER
# -----------------------------
encoder = OneHotEncoder(handle_unknown="ignore", sparse_output=False)

# learn only from train
encoder.fit(train)

# encode train
train_encoded = encoder.transform(train)

train_df = pd.DataFrame(
    train_encoded,
    columns=encoder.get_feature_names_out()
)

print("\nENCODED TRAIN DATA:\n", train_df)

# -----------------------------
# STEP 4: encode test (with unseen categories)
# -----------------------------
test_encoded = encoder.transform(test)

test_df = pd.DataFrame(
    test_encoded,
    columns=encoder.get_feature_names_out()
)

print("\nENCODED TEST DATA:\n", test_df)

FULL DATA:
         City     Plan  Device
0     Lahore    Basic  Mobile
1    Karachi  Premium  Laptop
2  Islamabad    Basic  Mobile
3     Lahore     Gold  Tablet
4    Karachi  Premium  Mobile
5     Multan    Basic   Watch

TRAIN DATA:
         City     Plan  Device
0     Lahore    Basic  Mobile
1    Karachi  Premium  Laptop
2  Islamabad    Basic  Mobile
3     Lahore     Gold  Tablet

TEST DATA:
       City   Plan  Device
0   Lahore  Basic  Mobile
1  NewCity    VIP      VR

ENCODED TRAIN DATA:
    City_Islamabad  City_Karachi  City_Lahore  Plan_Basic  Plan_Gold  \
0             0.0           0.0          1.0         1.0        0.0   
1             0.0           1.0          0.0         0.0        0.0   
2             1.0           0.0          0.0         1.0        0.0   
3             0.0           0.0          1.0         0.0        1.0   

   Plan_Premium  Device_Laptop  Device_Mobile  Device_Tablet  
0           0.0            0.0            1.0            0.0  
1           1.0    

In [ ]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

# ------------------------
# TRAIN DATA (known world)
# ------------------------
train = pd.DataFrame({
    "Color": ["Red", "Blue", "Green", "Red", "Blue"],
    "City": ["Lahore", "Karachi", "Lahore", "Islamabad", "Karachi"],
    "Plan": ["Basic", "Premium", "Basic", "Premium", "Basic"]
})

# ------------------------
# TEST DATA (includes unseen category: "NewCity", "Gold Plan")
# ------------------------
test = pd.DataFrame({
    "Color": ["Red", "Blue", "Green"],
    "City": ["Lahore", "NewCity", "Karachi"],   # unseen: NewCity
    "Plan": ["Basic", "Gold", "Premium"]        # unseen: Gold
})


encoder = OneHotEncoder(handle_unknown="ignore")


In [23]:
import pandas as pd

df = pd.DataFrame({
    "Color": ["Red", "Blue", "Green", "Red", "Blue", "Green"],
    "City": ["Lahore", "Karachi", "Lahore", "Islamabad", "Karachi", "Islamabad"],
    "Gender": ["Male", "Female", "Female", "Male", "Male", "Female"],
    "Plan": ["Basic", "Premium", "Basic", "Premium", "Basic", "Premium"]
})

print(df)

   Color       City  Gender     Plan
0    Red     Lahore    Male    Basic
1   Blue    Karachi  Female  Premium
2  Green     Lahore  Female    Basic
3    Red  Islamabad    Male  Premium
4   Blue    Karachi    Male    Basic
5  Green  Islamabad  Female  Premium


In [28]:
from sklearn.preprocessing import OneHotEncoder

# make encoder object 
encoder = OneHotEncoder(handle_unknown="ignore", sparse_output=False)
# now it wont give sparse output 


# fit + tranform 

encoded = encoder.fit_transform(df) 

# make df 

encoded_df = pd.DataFrame(
    encoded,
    columns=encoder.get_feature_names_out()
)

print(encoded_df)

   Color_Blue  Color_Green  Color_Red  City_Islamabad  City_Karachi  \
0         0.0          0.0        1.0             0.0           0.0   
1         1.0          0.0        0.0             0.0           1.0   
2         0.0          1.0        0.0             0.0           0.0   
3         0.0          0.0        1.0             1.0           0.0   
4         1.0          0.0        0.0             0.0           1.0   
5         0.0          1.0        0.0             1.0           0.0   

   City_Lahore  Gender_Female  Gender_Male  Plan_Basic  Plan_Premium  
0          1.0            0.0          1.0         1.0           0.0  
1          0.0            1.0          0.0         0.0           1.0  
2          1.0            1.0          0.0         1.0           0.0  
3          0.0            0.0          1.0         0.0           1.0  
4          0.0            0.0          1.0         1.0           0.0  
5          0.0            1.0          0.0         0.0           1.0  


In [30]:
# unseen data
train = df.iloc[:4]
test = pd.DataFrame({
    "Color": ["Red", "Blue"],
    "City": ["Lahore", "NewCity"],   # unseen
    "Gender": ["Male", "Female"],
    "Plan": ["Basic", "Premium"]
})

test

,Color,City,Gender,Plan
0,Red,Lahore,Male,Basic
1,Blue,NewCity,Female,Premium


In [33]:
# handling Unseen Data

encoder = OneHotEncoder(handle_unknown="ignore")

encoder.fit(train)
encoded_test  = encoder.transform(test).toarray()

encoded_test_df = pd.DataFrame(
    encoded_test,
    columns=encoder.get_feature_names_out()
)

print(encoded_test_df)

   Color_Blue  Color_Green  Color_Red  City_Islamabad  City_Karachi  \
0         0.0          0.0        1.0             0.0           0.0   
1         1.0          0.0        0.0             0.0           0.0   

   City_Lahore  Gender_Female  Gender_Male  Plan_Basic  Plan_Premium  
0          1.0            0.0          1.0         1.0           0.0  
1          0.0            1.0          0.0         0.0           1.0  
