# It is same as the LSTM ( 4_LSTM ) only line of code is changed

> Writing the Exact Code of LSTM 

> NOTE: To Understand the Code in Depth See the LSTM COde .. Everything is explained there

___
# Download the Dataset
___

In [1]:
import nltk

nltk.download("gutenberg")

[nltk_data] Downloading package gutenberg to /home/aizen/nltk_data...
[nltk_data]   Package gutenberg is already up-to-date!


True

___
# Load the Dataset
___

In [4]:
from nltk.corpus import gutenberg
import pandas as pd

In [5]:
# load the dataset
data = gutenberg.raw("shakespeare-hamlet.txt")

In [ ]:
# Adding  few more plays
hamlet   = gutenberg.raw('shakespeare-hamlet.txt')
macbeth  = gutenberg.raw('shakespeare-macbeth.txt')
caesar   = gutenberg.raw('shakespeare-caesar.txt')


## adding some more text
import requests

def get_gutenberg(url):
    r = requests.get(url)
    return r.text

# More Shakespeare from Project Gutenberg
othello  = get_gutenberg("https://www.gutenberg.org/files/1531/1531-0.txt")
lear     = get_gutenberg("https://www.gutenberg.org/files/1532/1532-0.txt")
macbeth2 = get_gutenberg("https://www.gutenberg.org/files/1533/1533-0.txt")  # Merchant of Venice



In [ ]:
# saving only hamlet
with open("hamlet.txt", "w") as file:
    file.write(data)

___
# Data Preprocessing
___

In [5]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

from sklearn.model_selection import train_test_split

In [ ]:
# load the saved Dataset
# with open("hamlet.txt", "r") as file:
#     text = file.read().lower()


# Loading the three plays ( the above code is same as LSTM where only hamlet was used)


text = (hamlet + macbeth + caesar + othello + lear + macbeth2).lower()

In [8]:
text

"[the tragedie of hamlet by william shakespeare 1599]\n\n\nactus primus. scoena prima.\n\nenter barnardo and francisco two centinels.\n\n  barnardo. who's there?\n  fran. nay answer me: stand & vnfold\nyour selfe\n\n   bar. long liue the king\n\n   fran. barnardo?\n  bar. he\n\n   fran. you come most carefully vpon your houre\n\n   bar. 'tis now strook twelue, get thee to bed francisco\n\n   fran. for this releefe much thankes: 'tis bitter cold,\nand i am sicke at heart\n\n   barn. haue you had quiet guard?\n  fran. not a mouse stirring\n\n   barn. well, goodnight. if you do meet horatio and\nmarcellus, the riuals of my watch, bid them make hast.\nenter horatio and marcellus.\n\n  fran. i thinke i heare them. stand: who's there?\n  hor. friends to this ground\n\n   mar. and leige-men to the dane\n\n   fran. giue you good night\n\n   mar. o farwel honest soldier, who hath relieu'd you?\n  fra. barnardo ha's my place: giue you goodnight.\n\nexit fran.\n\n  mar. holla barnardo\n\n   bar. 

___
### Tokenizor 
___

In [8]:
# tokenize the Text 

tokenizer = Tokenizer()
# Learn vocabulary from the text
# fit_on_texts() expects a list of strings
tokenizer.fit_on_texts([text]) # text needs to be given the inhe form of list

In [9]:
total_words = len(tokenizer.word_index) + 1  # 1 as 1 index is reserved for paddng

In [10]:
total_words

4818

In [11]:
tokenizer.word_counts

OrderedDict([('the', 993),
             ('tragedie', 4),
             ('of', 610),
             ('hamlet', 100),
             ('by', 105),
             ('william', 1),
             ('shakespeare', 1),
             ('1599', 1),
             ('actus', 2),
             ('primus', 1),
             ('scoena', 1),
             ('prima', 1),
             ('enter', 85),
             ('barnardo', 8),
             ('and', 862),
             ('francisco', 2),
             ('two', 22),
             ('centinels', 1),
             ("who's", 2),
             ('there', 76),
             ('fran', 8),
             ('nay', 26),
             ('answer', 9),
             ('me', 228),
             ('stand', 15),
             ('vnfold', 3),
             ('your', 253),
             ('selfe', 68),
             ('bar', 7),
             ('long', 17),
             ('liue', 15),
             ('king', 171),
             ('he', 196),
             ('you', 522),
             ('come', 104),
             ('most', 77),
  

In [12]:
tokenizer.word_index

{'the': 1,
 'and': 2,
 'to': 3,
 'of': 4,
 'i': 5,
 'you': 6,
 'a': 7,
 'my': 8,
 'it': 9,
 'in': 10,
 'that': 11,
 'ham': 12,
 'is': 13,
 'not': 14,
 'his': 15,
 'this': 16,
 'with': 17,
 'your': 18,
 'but': 19,
 'for': 20,
 'me': 21,
 'lord': 22,
 'as': 23,
 'what': 24,
 'he': 25,
 'be': 26,
 'so': 27,
 'him': 28,
 'haue': 29,
 'king': 30,
 'will': 31,
 'no': 32,
 'our': 33,
 'we': 34,
 'on': 35,
 'are': 36,
 'if': 37,
 'all': 38,
 'then': 39,
 'shall': 40,
 'by': 41,
 'thou': 42,
 'come': 43,
 'or': 44,
 'hamlet': 45,
 'good': 46,
 'do': 47,
 'hor': 48,
 'her': 49,
 'let': 50,
 'now': 51,
 'thy': 52,
 'how': 53,
 'more': 54,
 'they': 55,
 'from': 56,
 'enter': 57,
 'at': 58,
 'was': 59,
 'oh': 60,
 'like': 61,
 'most': 62,
 'there': 63,
 'well': 64,
 'know': 65,
 'selfe': 66,
 'would': 67,
 'them': 68,
 'loue': 69,
 'may': 70,
 "'tis": 71,
 'vs': 72,
 'sir': 73,
 'qu': 74,
 'which': 75,
 'did': 76,
 'why': 77,
 'laer': 78,
 'giue': 79,
 'thee': 80,
 'ile': 81,
 'must': 82,
 'hath': 

___
# Create Input Seqences
___

In [13]:
input_sequence = []
for line in text.split('\n'):  # `text.split('\n')` splits the complete text wherever a **new line** occurs.
                               # The loop processes one line at a time.
    token_list = tokenizer.texts_to_sequences([line])[0]  # The `[0]` removes the outer list:

    for i in range(1, len(token_list)):
        n_gram_sequence = token_list[:i+1]
        input_sequence.append(n_gram_sequence)

In [14]:
input_sequence

[[1, 687],
 [1, 687, 4],
 [1, 687, 4, 45],
 [1, 687, 4, 45, 41],
 [1, 687, 4, 45, 41, 1886],
 [1, 687, 4, 45, 41, 1886, 1887],
 [1, 687, 4, 45, 41, 1886, 1887, 1888],
 [1180, 1889],
 [1180, 1889, 1890],
 [1180, 1889, 1890, 1891],
 [57, 407],
 [57, 407, 2],
 [57, 407, 2, 1181],
 [57, 407, 2, 1181, 177],
 [57, 407, 2, 1181, 177, 1892],
 [407, 1182],
 [407, 1182, 63],
 [408, 162],
 [408, 162, 377],
 [408, 162, 377, 21],
 [408, 162, 377, 21, 247],
 [408, 162, 377, 21, 247, 882],
 [18, 66],
 [451, 224],
 [451, 224, 248],
 [451, 224, 248, 1],
 [451, 224, 248, 1, 30],
 [408, 407],
 [451, 25],
 [408, 6],
 [408, 6, 43],
 [408, 6, 43, 62],
 [408, 6, 43, 62, 1893],
 [408, 6, 43, 62, 1893, 96],
 [408, 6, 43, 62, 1893, 96, 18],
 [408, 6, 43, 62, 1893, 96, 18, 566],
 [451, 71],
 [451, 71, 51],
 [451, 71, 51, 1894],
 [451, 71, 51, 1894, 567],
 [451, 71, 51, 1894, 567, 378],
 [451, 71, 51, 1894, 567, 378, 80],
 [451, 71, 51, 1894, 567, 378, 80, 3],
 [451, 71, 51, 1894, 567, 378, 80, 3, 273],
 [451, 71

___
# Pad Sequences
___

In [15]:
# Find the Sentance with maximum length 
# then using Pad sequence make all the sentances the same length

max_sequence_len = max([len(x) for x in input_sequence]) 
max_sequence_len

14

In [16]:
input_sequence_padded = np.array(
    pad_sequences(
        input_sequence, maxlen = max_sequence_len, padding = "pre"

))

input_sequence_padded

array([[   0,    0,    0, ...,    0,    1,  687],
       [   0,    0,    0, ...,    1,  687,    4],
       [   0,    0,    0, ...,  687,    4,   45],
       ...,
       [   0,    0,    0, ...,    4,   45, 1047],
       [   0,    0,    0, ...,   45, 1047,    4],
       [   0,    0,    0, ..., 1047,    4,  193]],
      shape=(25732, 14), dtype=int32)

___
# Creating Predictors and Labels
___

> X and Y SPlit

In [17]:
import tensorflow as tf

X = input_sequence_padded[:,:-1] # take all the words except the Last Word of a sentance
y = input_sequence_padded[:,-1]  # Last word of every sentance

In [18]:
X

array([[   0,    0,    0, ...,    0,    0,    1],
       [   0,    0,    0, ...,    0,    1,  687],
       [   0,    0,    0, ...,    1,  687,    4],
       ...,
       [   0,    0,    0, ...,  687,    4,   45],
       [   0,    0,    0, ...,    4,   45, 1047],
       [   0,    0,    0, ...,   45, 1047,    4]],
      shape=(25732, 13), dtype=int32)

In [19]:
y

array([ 687,    4,   45, ..., 1047,    4,  193],
      shape=(25732,), dtype=int32)

In [20]:
y = tf.keras.utils.to_categorical(y, num_classes=total_words)

In [21]:
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(25732, 4818))

___
# Train Test Slit
___

In [22]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

___
# Model Training 
___

In [23]:
from tensorflow.keras.models  import Sequential
from tensorflow.keras.layers import Embedding,Dense,Dropout,GRU

In [ ]:
model = Sequential()

model.add(
    Embedding(total_words, 64, input_length=max_sequence_len-1)
)

model.add(
    GRU(100)          # single GRU, return_sequences=False
)

model.add(
    Dropout(0.3)      # dropout after GRU, not before last layer
)

model.add(
    Dense(total_words, activation="softmax")
)

/home/aizen/miniconda3/envs/gensim-env/lib/python3.12/site-packages/keras/src/layers/core/embedding.py:123: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(
E0000 00:00:1789795817.250487   20747 cuda_platform.cc:52] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)


In [25]:
model.compile(
    optimizer="adam",
    loss="categorical_crossentropy",
    metrics=["accuracy"]
)

In [ ]:
from tensorflow.keras.callbacks import EarlyStopping

early_stopping = EarlyStopping(
    monitor="val_loss",
    patience=3,
    restore_best_weights=True
)

In [ ]:
# Train Model 

history = model.fit(
    X_train,
    y_train,
    validation_data = (X_test, y_test),
    epochs = 50,
    callbacks = [early_stopping],
    verbose = 1
)

___
# Function to Predict Next Word 
___

In [1]:
def predict_next_word(model, tokenizer, text, max_sequence_len):
    """
    Predicts the next word given an input text sequence.

    Args:
        model        : Trained Keras LSTM model
        tokenizer    : Fitted Keras Tokenizer (maps words <-> integers)
        text         : Input string, e.g. "To be or not to be"
        max_sequence_len : Longest sequence the model was trained on (n_steps + 1)

    Returns:
        Predicted next word as string, or None if not found
    """

    # ----------------------------------------------------------------
    # STEP 1: Convert words to numbers
    # ----------------------------------------------------------------
    # The model doesn't understand words — only numbers.
    # texts_to_sequences turns each word into its assigned integer ID.
    #
    # Example:
    #   text = "to be or not"
    #   token_list = [2, 3, 5, 7]
    #
    # [0] at the end unpacks the outer list (we only passed one sentence).
    token_list = tokenizer.texts_to_sequences([text])[0]

    # ----------------------------------------------------------------
    # STEP 2: Trim if too long
    # ----------------------------------------------------------------
    # Model input has a fixed size (max_sequence_len - 1 steps).
    # If our token list is longer, keep only the LAST N tokens
    # because the most recent context matters most for next-word prediction.
    #
    # Example: max_sequence_len=5, token_list=[1,2,3,4,5,6]
    #          after trim → [3,4,5,6]  (last 4 tokens)
    if len(token_list) >= max_sequence_len:
        token_list = token_list[-(max_sequence_len - 1):]

    # ----------------------------------------------------------------
    # STEP 3: Pad to fixed length
    # ----------------------------------------------------------------
    # All model inputs must be the SAME length.
    # If our sequence is shorter than required, pad_sequences adds
    # zeros at the FRONT (padding="pre") to reach the required length.
    #
    # Example: maxlen=4, token_list=[3, 7]
    #          after padding → [[0, 0, 3, 7]]
    #
    # Result is 2D: [[...]] because model expects batch input.
    token_list = pad_sequences(
        [token_list],
        maxlen=max_sequence_len - 1,  # fixed input length model expects
        padding="pre"                 # zeros added at the beginning
    )

    # ----------------------------------------------------------------
    # STEP 4: Get model prediction
    # ----------------------------------------------------------------
    # model.predict() returns a probability for EVERY word in vocabulary.
    # Shape: (1, vocab_size) — one row (our sentence), many columns (words).
    #
    # Example (tiny vocab of 5 words):
    #   predicted = [[0.05, 0.10, 0.60, 0.20, 0.05]]
    #                  ^      ^      ^      ^      ^
    #                 word0  word1  word2  word3  word4
    predicted = model.predict(token_list, verbose=0)

    # ----------------------------------------------------------------
    # STEP 5: Pick the word with highest probability
    # ----------------------------------------------------------------
    # np.argmax finds the INDEX of the highest value.
    #   axis=1  → look across columns (words), not rows
    #   [0]     → unwrap from array to plain integer
    #   int()   → convert numpy int to Python int (for dict lookup)
    #
    # From the example above: argmax = 2  (word2 had 0.60 probability)
    predicted_word_index = int(np.argmax(predicted, axis=1)[0])

    # ----------------------------------------------------------------
    # STEP 6: Convert number back to word
    # ----------------------------------------------------------------
    # tokenizer.index_word is a dictionary: {integer: "word"}
    # It is the reverse of tokenizer.word_index: {"word": integer}
    #
    # .get() is safer than [] — returns None instead of crashing
    # if the index isn't found (e.g., index 0 is padding, not a real word).
    #
    # Example: index_word = {1: "to", 2: "be", 3: "or"}
    #          index 2 → "be"
    return tokenizer.index_word.get(predicted_word_index)

In [ ]:
input_text = "to be or to be not"
print(f"Input Text : {input_text}")

max_sequence_len = model.input_shape[1] + 1

next_word = predict_next_word(model, tokenizer, input_text, max_sequence_len)
print(f"Next Word Prediction : {next_word}")