# Numpy #
its a Mathematical liberary
performs operations including logical,sorting, selecting, linear Algebra, statistical opertions

- numpy has datatype -->> numpy array
- it has ndarray object ( nth dimentional Array)
- Homogeneous i.e all the element must have same datatype
- Its made in C language and used in python ( pandas, tensorflow etc also use numpy)

| Structure | Example             |
| --------- | ---------------     |
| Scalar    | `5`                 |
| Vector    | 1D `[1,2,3]`        |
| Matrix    | 2D `[[1,2],[3,4]]`  |
| Tensor    | 3D+ arrays          |

- Numpy Array has fixed at creation, Changing size of ndarray will create new array and delete Og array
- Elements in array needs to be of Sama data Type


In [ ]:
import numpy as np

# Creating Numpy Array #

## Using np.array([]) ##
    np.array() -->> it takes list == np.array([1,2,4])

- we can create 2D and 3D array Also.
                
                np.array([[1,2,3],[4,5,6]])  -->> 2D array   [[]] -->> it has two square opening and closing Brackets [[ ]]  ... has Rows and Cols

                array.shape -->> gives shape of array i.e (rows, colms)

                np.array([
                    [[1,2,3],[4,5,6]],  # we have two 2D arrays
                    [[6,7,8],[9,10,11]]
                    ])-->> 3D array [[[]]] -->> its like how many 2D arrays, here we have two 2D arrays

- dtype -->> we can make prefered datatype nparray using dtype

    * np.array([], dtype = datatype)

                np.array([1,2,4], dtype = float) -->> now array will be float

## Using arange() ##
* same as range we worked with in loops range()
* automatically create an array from starting range to ending range

        np.arange(start, end, step)   -->> np.arange(1,11) makes array from 1-10 elements

### Reshape(rows, cols) ###
- change given array to some other shape
- often used with arange()
-  imp rule: row and cols product must be equal to nmbr of elements present

        np.arange(start,end).reshape(row,col)   
        
        -->> np.arange(1,11).reshape(2,5) -->> (make it in 2 rows and 5 cols ) also 2*5 = 10 == nmbr of ele


## using np.ones() and np.zeros() ##
### np.ones((row,col)) ##
- makes array with only ones 
- provide a tuple where we define shape i.e np.ones((3,4)) -->> 3 rows and 4 cols

        np.ones((row,col))

### np.ones((row,col)) ##
- array on only zeros

        np.zeros((row,col))

## Using np.rando.random((row,col)) ##
- make array of random nmbrs beteen zero and one

        np.random.random((rows,cols))


## Using np.linspace(lower range, upper range, nmbr of ele) ##
- linerly spaced 
- elements are generated from lower to upper range at equal distance
- elements starts from lower range and last element is upper range and the elements are separated by equal distance

        np.linspace(lower range, upper range, nmbr of ele) 


## np.identity((col))
- makes identity matrix
- diagnals 1 and other ele zeros
- it makes array like if 3 is given then make 3x3 if 4 is given then 4x4

        np.identity((col))

In [ ]:
arr1 = np.array([1,2,3])  # it is 1D array
print(arr1)
print(type(arr1))  # <class 'numpy.ndarray'>

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
# 2D array   [[]] -->> it has two square opening and closing Brackets [[ ]]
# it has Rows and Colums So can be called Matrix
arr2d = np.array([[1,2,3],[4,5,6]])
print(arr2d)
print(arr2d.shape) # (2, 3) -->> (rows, colms) , so this array has 2 rows and 3 cols

[[1 2 3]
 [4 5 6]]
(2, 3)


In [ ]:
# 3D array  [[[]]] -->> it has 3 square opening and closing Brackets [[[ ]]]
# 3D array  [[[]]] -->> rits called Tenso
arr3d = np.array([
    [[1,2,3],[4,5,6]],  # we have two 2D arrays
    [[6,7,8],[9,10,11]]
])

print(arr3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [18]:
#dtype -->> we can make prefered data type array using dtype

a = np.array([1,2,3], dtype = float)
print(a) 

b = np.array([0, 1,2,4], dtype = bool)
print(b) # as 0 == False , other nmbrs == True

c = np.array([1,2,3], dtype= complex)
print(c)


[1. 2. 3.]
[False  True  True  True]
[1.+0.j 2.+0.j 3.+0.j]


# arange(start,end,steps)

In [ ]:
# arange -->> same as range() of loop
# arange(start, end, steps)

a1 = np.arange(1,11)
print(a1)

a2 = np.arange(2,9)
print(a2)

a3 = np.arange(1,20,2)
print(a3)

a4 = np.arange(0,21, 2)
print(a4)



[ 1  2  3  4  5  6  7  8  9 10]
[2 3 4 5 6 7 8]
[ 1  3  5  7  9 11 13 15 17 19]
[ 0  2  4  6  8 10 12 14 16 18 20]


In [30]:
#reshape  -->> change given array to some other shape
# always used with arange()

a5 = np.arange(1,11).reshape(5,2)  # reshape(row, cols)  make the given array in 5 rows and 2 cols
print(a5)                          # imp rule: row and cols product must be equal to nmbr of elements present ( here 5*2 = 10) 

print()
a6 = np.arange(1,11).reshape(2,5) # make it in 2 rows and 5 cols  
print(a6)

print()
a7 = np.arange(1,21).reshape(5,4)
print(a7)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


# np.ones((row,col)) #
# np.zeros((row, col)) #

In [36]:
# np.ones((row, col))
ones = np.ones((2,5))
print(ones)

print()
ones1 = np.ones((3,3))
print(ones1)

# np.zeros((row, col))

print()
z = np.zeros((3,4))
print(z)

print()
z1 = np.zeros((2,2))
print(z1)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[0. 0.]
 [0. 0.]]


#  np.random.random((rows,cols)) #

In [44]:
ran = np.random.random((2,4))
print(ran)

print()
ran1 = np.random.random((3,3))
print(ran1)

[[0.59193065 0.03576549 0.85872241 0.85251146]
 [0.506465   0.11080834 0.16634666 0.28950667]]

[[0.9755111  0.62502499 0.17545589]
 [0.14001799 0.62208226 0.34358458]
 [0.78296947 0.05700581 0.25741212]]


# np.linspace(lower range, upper range, nmbr of ele) 

In [ ]:
# np.linspace(lower range, upper range, nmbr of ele) 
lin = np.linspace(-10 , 10 , 10)
print(lin)

[-10.          -7.77777778  -5.55555556  -3.33333333  -1.11111111
   1.11111111   3.33333333   5.55555556   7.77777778  10.        ]


# np.identity((col))

In [ ]:
# np.identity((col))  

idt = np.identity(4)  # 4x4 array
print(idt)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Attributes #

## ndim ##
- tells no of Dimenstion of array

        array.ndim

## shape ##
- gives shape of array

                array.shape

- (row,col) -->> if (2,3) so 2 rows and 3 cols
- (row, col, nmbr of 2D arrays) -->> (3,2,2) so two 2 arrays of rows 3 and cols 2

## size ##
- nmbr of items 

                array.size

## itemsize ##
- how much space each item occupy in memory
        array.itemsize

## dtype ##
- what is datatype type of ur items
        
                array.dtype

# Changing Datatype of nparray #
- astype

                array.astype(datatype)
        
* array.astype(np.int32)

In [64]:
array1 = np.arange(1,11)
array2 = np.arange(0,12, dtype=float).reshape(3,4)
array3 = np.arange(8).reshape(2,2,2)

print(array1)

print()

print(array2)

print()

print(array3)

[ 1  2  3  4  5  6  7  8  9 10]

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [65]:
# ndim

print(array1.ndim)
print(array2.ndim)
print(array3.ndim)

1
2
3


In [66]:
# shape

print(array1.shape)
print(array2.shape)
print(array3.shape)

(10,)
(3, 4)
(2, 2, 2)


In [67]:
# size
print(array1.size)
print(array2.size)
print(array3.size)


10
12
8


In [ ]:
# itemsize 

print(array1.itemsize)
print(array2.itemsize) # as float and int occupy same space
print(array3.itemsize)

8
8
8


In [70]:
#dtype
print(array1.dtype)
print(array2.dtype)

int64
float64


In [ ]:
#astype

print(array1.dtype)
# now change

array1.astype(np.int32)



int64
int64
