# Array Operations #

## Arithmatic Operation ##
- works element by elment

                array1 + array2
                array1 - array2
                array1 * array2
                array1 / array2
                array1 ** array2

## Scalar Operations ##
-Operations between an array and single number.

        array + number
        array - number
        array * number
        array / number

- Its element wise i.e number will operate on each element 

## Comaparison Operations ##
- Comparison operations return Boolean arrays.

        array > value
        array < value
        array == value
        array >= value
        array <= value


## Aggregation Operations ##
- These operations reduce arrays into single values.

        [10, 20, 30, 40]
                ↓
                25

| Function     | Purpose            |
| -----------  | ------------------ |
| `np.sum()`   | sum                |
| `np.mean()`  | average            |
| `np.max()`   | maximum            |
| `np.min()`   | minimum            |
| `np.std()`   | standard deviation |
| `np.median()`| Median Value       |

        np.sum(array)  # gives sum of all elements of array


## Axis Operations ##
- Axis operations tell NumPy which direction to operate.
- row -> 1
- col -> 0

                np.sum(array, axis = 1)

                array = [
                        [ 1 3 4 ]
                        [ 3 2 2 ]
                ]

* print sum of all the rows i.e row1 = 1 + 3 + 4 = 8, row2 = 3 + 2 + 2 = 7

## Matrix Operation ##
- They involve operations between matrices (2D arrays).

| Operation             | Function                 |
| --------------------- | ------------------------ |
| Matrix multiplication | `A @ B` or `np.dot(A,B)` |
| Transpose             | `A.T`                    |
| Determinant           | `np.linalg.det(A)`       |
| Inverse               | `np.linalg.inv(A)`       |
| Eigenvalues           | `np.linalg.eig(A)`       |


### Dot Product ### 
- Rule: no of Cols of 1st array must be equal to no of rows of 2nd array
- shape: shape will be row of array 1 x col of array 2

[2 x 3 ] dot [ 3 x 2] 
     3 ======= 3      so dot product can be done and we'll get 2x2 array in result 


                A × B
        (number of columns in A) = (number of rows in B)


## log and Exponents #
- elemeent by element

                np.log(array)
                np.exp(array)

## Round / Floor / Ceil 
### Round ###
- Rounds numbers to the nearest value.

                np.round(array)

### Floor 
- eturns the largest integer less than or equal to the number.

                np.floor(array)

### Ceil 
- Returns the smallest integer greater than or equal to the number.

                np.ceil(array)


# Functions #
## Reshaping ##
### reshape
- We already studied this

### Transpose ##
- interchange row and col 

                np.transpose(array)
                      or
                array.T
### ravel ###
- Convert Array in 1D ( no matter the dimention)

                array.ravel()


# Stacking #
- Merge numpy array
- oining arrays along a particular axis.

| Function            | Purpose              |
| ------------------- | -------------------- |
| `np.vstack()`       | stack vertically     |
| `np.hstack()`       | stack horizontally   |
| `np.stack()`        | stack along new axis |
| `np.column_stack()` | stack columns        |
| `np.row_stack()`    | stack rows           |


## Vertical Stack #
- Combine arrays row-wise (one on top of another).

                np.vstack((array1, array2))

## Horizontal Stack 
- Combine arrays side by side.

                np.hstack((array1, array2))

# Spliting #
- Diving Array in equal parts

| Function           | Purpose                      |
| ------------------ | ---------------------------- |
| `np.split()`       | General splitting            |
| `np.array_split()` | Uneven splits allowed        |
| `np.hsplit()`      | Split horizontally (columns) |
| `np.vsplit()`      | Split vertically (rows)      |
| `np.dsplit()`      | Split depth (3D arrays)      |


## Vertical Split ##
- Splits by rows.

        np.vsplit(array, parts)

## Horizontal split ## 
- Splits by cols.

        np.hsplit(array, parts)

In [2]:
import numpy as np

# Arithmatic Operations #

In [33]:
arr1 = np.arange(1,6)
arr2 = np.arange(6,11)

print(arr1)
print(arr2)

print()
print( arr1 + arr2 ) # element by element 
print( arr1 - arr2)
print(arr1 * arr2)
print( arr1 / arr2)


[1 2 3 4 5]
[ 6  7  8  9 10]

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


# Scalar Operations #

In [6]:
a = np.array([1,2,3,4,5])

print(a)

print(a+5)
print(a-2)
print(a*2)


[1 2 3 4 5]
[ 6  7  8  9 10]
[-1  0  1  2  3]
[ 2  4  6  8 10]


# Comaparison Operations

In [10]:
a1 = np.arange(10)

print(a1)

print(a1 > 5)
print(a1 == 7)
print(a1 >= 8)

[0 1 2 3 4 5 6 7 8 9]
[False False False False False False  True  True  True  True]
[False False False False False False False  True False False]
[False False False False False False False False  True  True]


# Aggregation Operations

In [15]:
a2 = np.arange(1,12)

print(a2)

print(np.sum(a2)) # sum of all elements in array
print(np.prod(a2))
print(np.max(a2))
print(np.min(a2))

[ 1  2  3  4  5  6  7  8  9 10 11]
66
39916800
11
1


# Axis Operation

In [26]:
data = np.array([
 [1,2,3],
 [4,5,6],
 [7,8,9]
])

print(data)  # its a 2D array 

print()
# I want to calculate sum of only rows
print(np.sum(data, axis=1))  # sum each ele in row1 = 1+2+3 = 6 , row2 = 15, row3 = 24

#cols
print(np.sum(data, axis = 0))

# prod
print("prod")
print(np.prod(data, axis = 1))
print(np.prod(data, axis = 0))

#max
print("max")
print(np.max(data, axis = 1))
print(np.max(data, axis = 0))

# min
print("min")
print(np.min(data, axis = 1))
print(np.min(data, axis = 0))



[[1 2 3]
 [4 5 6]
 [7 8 9]]

[ 6 15 24]
[12 15 18]
prod
[  6 120 504]
[ 28  80 162]
max
[3 6 9]
[7 8 9]
min
[1 4 7]
[1 2 3]


# Matrix Operation #
## Dot Product #


In [ ]:
# dot product 

A = np.arange(1,11).reshape(2,5)   # 5 == 5  satisfied
B = np.arange(11,21).reshape(5,2)  # shape 2x2

print(A)
print()
print(B)

dot = np.dot(A,B)

print()
print(dot)
print()

A1 = np.arange(6).reshape(3,2)
B1 = np.arange(6,12).reshape(2,3) # shape 3x3

print(A1)
print()
print(B1)

dot1 = np.dot(A1,B1)
print()
print(dot1)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

[[11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]

[[245 260]
 [620 660]]

[[0 1]
 [2 3]
 [4 5]]

[[ 6  7  8]
 [ 9 10 11]]

[[ 9 10 11]
 [39 44 49]
 [69 78 87]]


# Log and Exponents 

In [13]:

A2 = np.array([[1,2,3],
              [4,5,6]])

np.log(A2)
np.exp(A2)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

# Round/Floor/Ceil

In [16]:
arr3 = np.array([1.2, 2.6, 3.5, 4.3])

print(np.round(arr3))

print()

print(np.floor(arr3))

print()

print(np.ceil(arr3))

[1. 3. 4. 4.]

[1. 2. 3. 4.]

[2. 3. 4. 5.]


# Functions#
# transpose and Ravel

In [17]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

print("\n1D : \n", a1)
print("\n2D : \n", a2)
print("\n3D : \n", a3)


1D : 
 [0 1 2 3 4 5 6 7 8 9]

2D : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

3D : 
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [21]:
# Transpose
print( np.transpose(a2))
print( a2.T)
print()

# ravel

print( a2.ravel())
print( a3.ravel())

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[0 1 2 3 4 5 6 7]


# Stacking 

In [25]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a)
print("\n", b , "\n Vertical Stacking")


v_stack = np.vstack((a,b))
print(v_stack)

print("\n Horizontal Stacking ")
h_stack = np.hstack((a,b))
print(h_stack)

[1 2 3]

 [4 5 6] 
 Vertical Stacking
[[1 2 3]
 [4 5 6]]

 Horizontal Stacking 
[1 2 3 4 5 6]


# Spliting

In [28]:
a = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])

print(a)
print()
print("Vertical Spliting")

v_split = np.vsplit(a,3)
print(v_split)

print()
print("Horizontal Spliting")

h_split = np.hsplit(a,4)
print(h_split)



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Vertical Spliting
[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]

Horizontal Spliting
[array([[1],
       [5],
       [9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]]), array([[ 4],
       [ 8],
       [12]])]
