# Indexing # 
- Same Concept We Learned in Cpp for 1D, 2D, and 3D

        array[index]

- Positive Indexing: Move from Left to Right -->> Starts from Zeros

- Negative Indexing: move from right to left -->> starts from -1

## 2D ##

        array[row_index, column_index]

## 3D ##
        array[layer, row, column]


# Slicing #
- Slicing extracts ranges of elements.

                array[start : stop : step]
- start → starting index
- stop → ending index (excluded)
- step → jump

## 2D ##

        array[row_slice , column_slice]
- Each slice Follow

                start : stop : step

                :  → means everything

## 3D ## 
        array[layer_slice , row_slice , column_slice]

- Each slice Follow

                start : stop : step

                :  → means everything

In [1]:
import numpy as np

In [4]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

print("\n1D : \n", a1)
print("\n2D : \n", a2)
print("\n3D : \n", a3)


1D : 
 [0 1 2 3 4 5 6 7 8 9]

2D : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

3D : 
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [ ]:
print(a1[0])
print(a1[3])
print(a1[-1])
print()
#2D

print(a2[1,2]) # prints 6
print(a2[2,0]) # 8
print(a2[0,3]) # 3
print(a2[2,3]) # 11

print()
#3D -->> array[layer, row , col]

print(a3[0,1,1]) # 3
print(a3[1,0,0]) # 4
print(a3[1,0,1]) # 5

0
3
9

6
8
3
11

3
4
5


# Slicing #

In [16]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

print("\n1D : \n", a1)
print("\n2D : \n", a2)
print("\n3D : \n", a3)


1D : 
 [0 1 2 3 4 5 6 7 8 9]

2D : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

3D : 
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [20]:
# extract 2,3,4 from a1

print( a1[2:5] )  # last index not included -->> from 2-4
print( a1[2:6:2])
print( a1[1:9])

[2 3 4]
[2 4]
[1 2 3 4 5 6 7 8]


# 2D sliciing

In [22]:
#2D -->> array[row_slice , column_slice]
a2 = np.arange(12).reshape(3,4)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
# extract the 1st row only 
print( a2[0,:]) # I want 1st row so row=0, in 1st Row I want all the Cols so Col = : (means) all

# extract 3rd Col
print( a2[:, 2]) # i want all the rows ( : ) of Col 2 so col = 2

# exract 5,6
#        9,10

print( a2[1:3,1:3]  ) # I want row 1 and 2 so 1:3 as last is not included
                      # I want col 1 and 2 so 1:3 as last is not included 

# exract 2,3
#        6,7

print( a2[0:2 , 2:] ) # I want row 0 and 1 so 0:2
                      # I want col 2 and 3 so 2: means onwards from 2 ( all )
# extract 0 - - 3 
#         8 - - 11  4 corners items 

print( a2[::2, ::3] )  # Each slice follow start : stop : step 


[0 1 2 3]
[ 2  6 10]
[[ 5  6]
 [ 9 10]]
[[2 3]
 [6 7]]
[[ 0  3]
 [ 8 11]]


In [31]:
A = np.array([
 [ 1,  2,  3,  4,  5],
 [ 6,  7,  8,  9, 10],
 [11, 12, 13, 14, 15],
 [16, 17, 18, 19, 20],
 [21, 22, 23, 24, 25]
])

print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [44]:
#1  2  3  4  5 r1
#6  7  8  9 10  r2

print( A[:2, :]) # 
print()

print( A[3:, :])
print()

# 7   8   9
#12 13 14
#17 18 19
 
print( A[1:4, 1:4])  #rows 1 → 3, cols 1 → 3
print()

# Every Second Row
print( A[::2, :] )  # step 2 across rows
print()

# Every Second Column
print( A[:, ::2] )
print()

# Extract the Four Corners
print( A[::4, ::4] )
print()
# Border of Matrix
#1  2  3  4  5
#6           10
#11          15
#16          20
#21 22 23 24 25

top = A[0, :]
bottom = A[4, :]
left = A[:, 0]
right = A[:, 4]

print(top,left,bottom, right)
print()


#7  9
#17 19

print( A[1:4:2, 1:4:2] )

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

[[16 17 18 19 20]
 [21 22 23 24 25]]

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]

[[ 1  2  3  4  5]
 [11 12 13 14 15]
 [21 22 23 24 25]]

[[ 1  3  5]
 [ 6  8 10]
 [11 13 15]
 [16 18 20]
 [21 23 25]]

[[ 1  5]
 [21 25]]

[1 2 3 4 5] [ 1  6 11 16 21] [21 22 23 24 25] [ 5 10 15 20 25]

[[ 7  9]
 [17 19]]


# 3D

In [46]:
a3 = np.arange(27).reshape(3,3,3)
print("\n3D : \n", a3)


3D : 
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [55]:
# Extract 2nd 2D array
print( a3[1] )
print()
# Extract 1st and last 2D array

print( a3[::2])
print()

# Extract 2nd row of 1st 2d Array
print( a3[0, 1, :] )
print()

#Extract 2nd col of 2nd 2D 
print( a3[1, :, 1] )
print()

# extraxt 22,23,25,26 from 3rd 2DArray
print( a3[2, 1:, 1:] )
print()

# Extract 0,2 18,20
print( a3[::2, 0, ::2 ])
print()


[[ 9 10 11]
 [12 13 14]
 [15 16 17]]

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

[3 4 5]

[10 13 16]

[[22 23]
 [25 26]]

[[ 0  2]
 [18 20]]



# Iteration #
 - 1D prints one ele in each iteration
 - 2D prints one row in each iteration
 - 3D prints one 2D array in each iteration

## Element by Element 
- if you want to print ele by ele in high dimentional array 

        np.nditer(array)

- this make looping ele by ele

In [56]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

print("\n1D : \n", a1)
print("\n2D : \n", a2)
print("\n3D : \n", a3)


1D : 
 [0 1 2 3 4 5 6 7 8 9]

2D : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

3D : 
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [59]:
# 1D prints one ele in each iteration
for i in a1:
    print(i)

# 2D prints one row in each iteration
print("\n 2D \n")
for i in a2:
    print(i)

# 3D prints one 2D array in each iteration
print("\n 3D \n")
for i in a3:
    print(i)




0
1
2
3
4
5
6
7
8
9

 2D 

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]

 3D 

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


In [61]:
for i in np.nditer(a3):
    print(i)

print()

for i in np.nditer(a2):
    print(i)

0
1
2
3
4
5
6
7

0
1
2
3
4
5
6
7
8
9
10
11
