# Fancy Indexing #
- Some times we can't Pattern (like skip 1,2,3 .. rows Cols whch can be done using Steps)
- so we use Fancy Indexing : Here we can Tell which specific Row, Col we want even with no pattern like row 1,5,6,8,17
- for ID it can be said for Elements 

### 1D 
        array[[index1, index2, index3]]
array[ [] ] -->> gives list [] inside

### 2D 
        array[[rows]]   -->> in col not given then it takes rows
        array[[row_indexes], [col_indexes]]


## Boolean Indexing ##
- Boolean indexing selects elements based on conditions.

                > < >= <= == !=
                syantax: array[condition]

## Multiple Coditions 
- &  → AND
- |  → OR
- ~  → NOT

        array[ (condition 1 ) & (condition 2 )]

# Fancy indexing

In [1]:
import numpy as np

In [ ]:
a = np.random.randint(1,20, 10) # ranint(start range, end range, nmber of random items)
print(a)


[12  4  9 19  8  3  3 11  1 12]


In [6]:
print( a[ [ 0,3,6,8,9] ]) # only prints these indexes 
print( a[ [1,2,9,0] ] )
print( a[[8,0,1,2,3] ] )
print( a[ [ 1,2,3 ] ])

[12 19  3  1 12]
[ 4  9 12 12]
[ 1 12  4  9 19]
[ 4  9 19]


In [8]:
# 2D
a1 = np.arange(24).reshape(6,4)
print(a1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [24]:
# extract 1,2,,5,6 rows
print( a1[ [0,1,4,5 ] ])
print()
print(a1[[1,2,5]])
print()

# Extract 0,2,3 cols
print( a1[:,[0,2,3]])
print()
print( a1[:,[1,2]])
print()

print(a1[[0,1,2],[2,1,0]]) #print specific element giving row and col index
print()  # row 0, col2 : row 1 col 1 : row 2 col 0

print(a1[[4,2],[0,1]]) #16 and 9
print()

print( a1[[1,2,5]])
print()
print(a1[:,[1,3]])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [16 17 18 19]
 [20 21 22 23]]

[[ 4  5  6  7]
 [ 8  9 10 11]
 [20 21 22 23]]

[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]
 [12 14 15]
 [16 18 19]
 [20 22 23]]

[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]
 [17 18]
 [21 22]]

[2 5 8]

[16  9]

[[ 4  5  6  7]
 [ 8  9 10 11]
 [20 21 22 23]]

[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]
 [17 19]
 [21 23]]


# Boolean Indexing #

In [25]:
a2 = np.random.randint(1,20,8)
print(a2)

[ 9  1 19 12  5  9  3 16]


In [ ]:
print(a[a>5]) # print elemenst greater than 5
print(a[a==19])
print( a[a<=8] )
print(a[(a>5) & (a%2 == 0)])
print( a[ (a<25) | (a>2)])


[12  9 19  8 11 12]
[19]
[4 8 3 3 1]
[12  8 12]
[12  4  9 19  8  3  3 11  1 12]


In [34]:
# 2D
a1 = np.arange(24).reshape(6,4)
print(a1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [37]:
print(a1[a1<9])
print(a1[ (a1>= 5 ) & ( a1 <=10 )])
print(a1 [ (a1 >= 6 ) & (a1 % 2 != 0)])

[0 1 2 3 4 5 6 7 8]
[ 5  6  7  8  9 10]
[ 7  9 11 13 15 17 19 21 23]
