In [1]:
import numpy as np

# creating array

In [14]:
np.arange(10)
np.arange(12).reshape(2,6)
np.arange(24).reshape(2,12)
np.random.randint(2,10,5)
np.random.randint(1,20,10)
np.linspace(2,10,4)
np.random.randint(3,30,20)
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [2]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# Operation

In [20]:
a + 2
a - 2 
a * 2
a > 6

array([[False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True]])

In [29]:
np.sum(a)
np.min(a)
np.max(a)
np.sum(a, axis=1) # sum of each row
np.max(a, axis=1)
np.min(a, axis=1)
np.mean(a, axis=1)
np.median(a, axis=0)
np.sum(a, axis=0)

array([12, 15, 18, 21])

In [3]:
b = np.arange(12,24).reshape(4,3)
b

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

# matrix Operations

In [47]:
np.dot(a,b)
a.T # transpose
b.T
np.dot(b,a)
np.log(a)
np.exp(b)
np.ceil(a)
np.floor(b)
np.round(a)
np.dot(a,b)
np.ravel(a)
np.ravel(b)
a.T
b.T



/tmp/ipykernel_10972/4140145146.py:5: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([[12, 15, 18, 21],
       [13, 16, 19, 22],
       [14, 17, 20, 23]])

In [4]:
a1 = np.array([1,2,3])
b1 = np.array([4,5,6])

np.vstack((a1,b1))
np.vstack((b1,a1))

np.hstack((a1,b1))

array([1, 2, 3, 4, 5, 6])

# slicing 

In [5]:
a1 = np.arange(10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [83]:
a[0,0]
a[1,2]

a1[0:5]
a1[2:9]
a1[::2]

# 2D
a[0,:] # only 1st row 
a[:,1] # only the 1st col

a[1:3, 1:3 ]
a[0:2, 2:4]
a[0:3:2, 0:4:3]

# 3D
a3[1,:,:]
a3[0, 1:2, :] ## Extract 2nd row of 1st 2d Array
a3[::2, 0:1, ::2] # Extract 0,2 18,20

# Fancy 2D

a[[1,2]] # extract row 1 and 2
a[:, [1,2]] # extract col 1,2
a[[0,1,2],[3,1,0]]
a[[1,2,1],[2,2,1]]

# Boolean
a[ a>2 ]
a[ (a>2) & (a<7)]
a[  (a>=5 & (a+2 <= 7))]




array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

# broadcasting

In [8]:
a6 = np.arange(3).reshape(1,3)  # ( 1, 3 ) -->> (1->2->3 , 3) -->> (3,3)
b6 = np.arange(3).reshape(3,1)  # ( 3, 1 ) -->> (3,  1->2->3) --->> (3,3)
#                                  increment the one and match its coresponding nmbrs 

print( a6* b6 )


[[0 0 0]
 [0 1 2]
 [0 2 4]]


In [9]:
a5 = np.arange(12).reshape(3,4)  # (3,4)
b5 = np.arange(3) # (,3) -->> (1,3) -->> ( 3, 3 ) shapes didnt match so won't broadcast 
#                  we can only increament 1
print(a5)
print("\n", b5)

print( a5 + b5 )

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 [0 1 2]


ValueError: operands could not be broadcast together with shapes (3,4) (3,) 