___

# Logistic Regression 
    Binary Classification 
___

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns
%matplotlib inline


In [2]:
# we will create a Data using sklearn 
# Create Data Set for  Classification problem

from sklearn.datasets import make_classification

In [3]:
# Create the Dataset using Make_classification 
X, y = make_classification(n_samples=10000, n_features=10, n_classes=2, random_state= 42)

# n_samples : nmbr of datapoits
# n_features : nmbr of independednt features 
# n_classes : how many classes of output feature ( we select 2 so binary )

# this will return data into section independet X and  Y dependent 


In [ ]:
X
# see the features are already standardized ( we dont need to implemet scaler on it )

array([[ 0.63356292,  0.35738502, -0.50393083, ...,  2.08168408,
         0.04126585, -0.25829761],
       [ 1.28390452,  1.10945943, -0.90895257, ..., -0.17220012,
         1.1503591 ,  0.14774397],
       [-0.966476  , -0.59331416,  0.45802021, ...,  0.43447665,
         0.4236775 ,  1.2513799 ],
       ...,
       [ 0.84146796, -0.59374928, -0.39167125, ...,  0.28933544,
        -0.43435776, -1.27133487],
       [ 1.08025182, -0.60776141, -0.48860471, ...,  0.29149633,
         0.82797965, -1.06939928],
       [-1.20533758, -1.71964714,  0.99435846, ..., -0.30581946,
        -1.40572814, -0.70320688]], shape=(10000, 10))

In [5]:
pd.DataFrame(X)

,0,1,2,3,4,5,6,7,8,9
0,0.633563,0.357385,-0.503931,0.935066,0.647981,-0.050796,-1.933989,2.081684,0.041266,-0.258298
1,1.283905,1.109459,-0.908953,1.006586,0.492219,1.107295,1.243526,-0.172200,1.150359,0.147744
2,-0.966476,-0.593314,0.458020,1.032323,1.283685,-0.317640,1.499045,0.434477,0.423678,1.251380
3,2.429309,-1.306530,-1.869925,3.092164,2.028800,-0.879635,-0.393494,-0.101213,-1.624066,0.443553
4,-1.204798,0.078464,0.705181,0.224765,0.618707,1.534946,-0.302288,2.325055,0.495505,0.538133
...,...,...,...,...,...,...,...,...,...,...
9995,-1.606404,0.228927,0.959690,0.145821,0.682755,-0.927143,-0.280438,0.789222,-1.330100,-1.463687
9996,1.154048,-0.120265,-0.643621,-0.467386,-0.825604,0.725398,-1.439272,-1.132146,1.511610,-0.114986
9997,0.841468,-0.593749,-0.391671,-0.955036,-1.169619,0.683856,-1.629486,0.289335,-0.434358,-1.271335
9998,1.080252,-0.607761,-0.488605,-1.338506,-1.605447,-1.689724,0.202908,0.291496,0.827980,-1.069399


___
# Train Test Split
___


In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X_train, X_test, y_train , y_test = train_test_split(X, y, test_size=0.30 , random_state=42)

___
# Model Training 
___

In [8]:
from sklearn.linear_model import LogisticRegression

In [9]:
model = LogisticRegression()
model.fit(X_train, y_train)

,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add a L2 penalty term and it is the default choice;- `'l1'`: add a L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'` and `l1_ratio` set to any float between 0 and 1 for `'penalty='elasticnet'`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation `) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",None
,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary ` for details.",None
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is 'lbfgs'.To choose a solver, you might want to consider the following aspects:- 'lbfgs' is a good default solver because it works reasonably well for a wide class of problems.- For :term:`mul

In [10]:
y_pred = model.predict(X_test)

In [11]:
print("actual Values: ", y_test)
print("predicted Data : ", y_pred)

actual Values:  [1 1 1 ... 0 0 0]
predicted Data :  [1 1 1 ... 0 1 0]


In [12]:
# this gives us probabilty 
model.predict_proba(X_test)

array([[0.01640705, 0.98359295],
       [0.11288143, 0.88711857],
       [0.11091352, 0.88908648],
       ...,
       [0.95175071, 0.04824929],
       [0.47883592, 0.52116408],
       [0.97621358, 0.02378642]], shape=(3000, 2))

___
# Performance Matrix
___

In [13]:
from sklearn.metrics import accuracy_score , confusion_matrix, classification_report

In [14]:
score = accuracy_score(y_test, y_pred)
print(score)

0.8923333333333333


In [15]:
# Confusion matrix .. since this is binar classification we'll get  2x2 matrix
confusion_mtrx = confusion_matrix(y_test, y_pred)
print(confusion_mtrx)

[[1329  155]
 [ 168 1348]]


In [16]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.89      0.90      0.89      1484
           1       0.90      0.89      0.89      1516

    accuracy                           0.89      3000
   macro avg       0.89      0.89      0.89      3000
weighted avg       0.89      0.89      0.89      3000



____

# Hyper Parameter Tuning  and Cross Validation
___

___
___

# Hyperparameters of Logistic Regression

Hyperparameters are settings that you choose **before training** the Logistic Regression model.

They control how the model learns.

---

# Scikit-Learn Syntax

```python
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(
    penalty="l2",
    C=1.0,
    solver="lbfgs",
    max_iter=100,
    random_state=42
)

model.fit(X_train, y_train)
```

---

# 1. `penalty`

Controls the type of regularization.

```python
penalty="l2"
```

Possible values:

| Value          | Meaning                        |
| -------------- | ------------------------------ |
| `"l2"`         | Ridge Regularization (Default) |
| `"l1"`         | Lasso Regularization           |
| `"elasticnet"` | Elastic Net                    |
| `None`         | No regularization              |

Example:

```python
LogisticRegression(penalty="l1")
```

---

# 2. `C`

The **inverse of regularization strength**.

```python
C=1.0
```

Think of it like this:

```text
Small C
    ↓
More Regularization

Large C
    ↓
Less Regularization
```

Examples:

```python
C=0.01
```

Very strong regularization.

```python
C=1
```

Default.

```python
C=100
```

Almost no regularization.

---

# 3. `solver`

Algorithm used to optimize (train) the model.

```python
solver="lbfgs"
```

Common solvers:

| Solver        | Supports                            |
| ------------- | ----------------------------------- |
| `"lbfgs"`     | L2, Multiclass (Default)            |
| `"liblinear"` | Small datasets, L1 & L2             |
| `"saga"`      | L1, L2, Elastic Net, Large datasets |
| `"newton-cg"` | L2                                  |
| `"sag"`       | Large datasets                      |

Example:

```python
solver="liblinear"
```

---

# 4. `max_iter`

Maximum number of training iterations.

```python
max_iter=100
```

If you see:

```text
ConvergenceWarning:
```

Increase it.

Example:

```python
max_iter=1000
```

---

# 5. `random_state`

Controls randomness.

```python
random_state=42
```

Used for reproducible results.

---

# 6. `class_weight`

Useful for imbalanced datasets.

```python
class_weight="balanced"
```

Example:

```text
Normal Emails : 950

Spam Emails : 50
```

Without balancing:

The model may predict almost everything as **Normal**.

With:

```python
class_weight="balanced"
```

Both classes receive appropriate importance.

---

# 7. `multi_class`

Controls multiclass classification strategy.

Example:

```python
multi_class="ovr"
```

Possible values:

| Value           | Meaning                |
| --------------- | ---------------------- |
| `"ovr"`         | One-vs-Rest            |
| `"multinomial"` | Softmax Classification |

> **Note:** In newer versions of Scikit-Learn, `multi_class` is often selected automatically based on the solver.

---

# Complete Example

```python
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(
    penalty="l2",
    C=1.0,
    solver="lbfgs",
    max_iter=500,
    random_state=42
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)
```

---

# Most Important Hyperparameters

| Hyperparameter | Purpose                     |
| -------------- | --------------------------- |
| `penalty`      | Type of regularization      |
| `C`            | Strength of regularization  |
| `solver`       | Optimization algorithm      |
| `max_iter`     | Maximum training iterations |
| `class_weight` | Handle imbalanced classes   |
| `random_state` | Reproducible results        |

---

# Rule of Thumb

* **`penalty`** → Choose the regularization method.
* **`C`** → Controls how strong the regularization is.
* **`solver`** → Choose the optimization algorithm.
* **`max_iter`** → Increase if the model doesn't converge.
* **`class_weight="balanced"`** → Use for imbalanced datasets.

---

## One-Line Definition

> Logistic Regression hyperparameters control **how the model learns**, **how much regularization is applied**, and **how the optimization process is performed** before training begins.


____
____

In [18]:
from sklearn.linear_model import LogisticRegression

In [ ]:
model = LogisticRegression()

penalty = ["l1", "l2", "elasticnet"]
c_values = [100,10,1.0,0.1,0.01]
solver = ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga']

# above are all the paramters: we will check which one is best for our dataset


In [22]:
params = dict( penalty = penalty, C = c_values, solver = solver )
params

{'penalty': ['l1', 'l2', 'elasticnet'],
 'C': [100, 10, 1.0, 0.1, 0.01],
 'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga']}

In [24]:
# Grid Search Cv
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import StratifiedKFold

In [25]:
cv = StratifiedKFold()

In [ ]:
grid = GridSearchCV(estimator=model, param_grid=params, scoring='accuracy', cv = cv, n_jobs= -1)

# grid find the best combination of parameter

In [27]:
grid.fit(X_train, y_train)

/home/aizen/AI_ML/env/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/aizen/AI_ML/env/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/aizen/AI_ML/env/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this w

,"estimator estimator: estimator objectThis is assumed to implement the scikit-learn estimator interface.Either estimator needs to provide a ``score`` function,or ``scoring`` must be passed.",LogisticRegression()
,"param_grid param_grid: dict or list of dictionariesDictionary with parameters names (`str`) as keys and lists ofparameter settings to try as values, or a list of suchdictionaries, in which case the grids spanned by each dictionaryin the list are explored. This enables searching over any sequenceof parameter settings.","{'C': [100, 10, ...], 'penalty': ['l1', 'l2', ...], 'solver': ['newton-cg', 'lbfgs', ...]}"
,"scoring scoring: str, callable, list, tuple or dict, default=NoneStrategy to evaluate the performance of the cross-validated model onthe test set.If `scoring` represents a single score, one can use:- a single string (see :ref:`scoring_string_names`);- a callable (see :ref:`scoring_callable`) that returns a single value;- `None`, the `estimator`'s :ref:`default evaluation criterion ` is used.If `scoring` represents multiple scores, one can use:- a list or tuple of unique strings;- a callable returning a dictionary where the keys are the metric names and the values are the metric scores;- a dictionary with metric names as keys and callables as values.See :ref:`multimetric_grid_search` for an example.",'accuracy'
,"n_jobs n_jobs: int, default=NoneNumber of jobs to run in parallel.``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.``-1`` means using all processors. See :term:`Glossary `for more details... versionchanged:: v0.20 `n_jobs` default changed from 1 to None",-1
,"refit refit: bool, str, or callable, default=TrueRefit an estimator using the best found parameters on the wholedataset.For multiple metric evaluation, this needs to be a `str` denoting thescorer that would be used to find the best parameters for refittingthe estimator at the end.Where there are considerations other than maximum score inchoosing a best estimator, ``refit`` can be set to a function whichreturns the selected ``best_index_`` given ``cv_results_``. In thatcase, the ``best_estimator_`` and ``best_params_`` will be setaccording to the returned ``best_index_`` while the ``best_score_``attribute will not be available.The refitted estimator is made available at the ``best_estimator_``attribute and permits using ``predict`` directly on this``GridSearchCV`` instance.Also for multiple metric evaluation, the attributes ``best_index_``,``best_score_`` and ``best_params_`` will only be available if``refit`` is set and all of them will be determined w.r.t this specificscorer.See ``scoring`` parameter to know more about multiple metricevaluation.See :ref:`sphx_glr_auto_examples_model_selection_plot_grid_search_digits.py`to see how to design a custom selection strategy using a callablevia `refit`.See :ref:`this example`for an example of how to use ``refit=callable`` to balance modelcomplexity and cross-validated score... versionchanged:: 0.20 Support for callable added.",True
,"cv cv: int, cross-validation generator or an iterable, default=NoneDetermines the cross-validation splitting strategy.Possible inputs for cv are:- None, to use the default 5-fold cross validation,- integer, to specify the number of folds in a `(Stratified)KFold`,- :term:`CV splitter`,- An iterable yielding (train, test) splits as arrays of indices.For integer/None inputs, if the estimator is a classifier and ``y`` iseither binary or multiclass, :class:`StratifiedKFold` is used. In allother cases, :class:`KFold` is used. These splitters are instantiatedwith `shuffle=False` so the splits will be the same across calls.Refer :ref:`User Guide ` for the variouscross-validation strategies that can be used here... versionchanged:: 0.22 ``cv`` default value if None changed from 3-fold to 5-fold.",StratifiedKFo...shuffle=False)
,"verbose verbose: intControls the verbosity: the higher, the more messages.- >1 : the computation time for each fold and parameter candida

In [ ]:
# Now see which paramters are the best 
grid.best_params_

# so output are best parameter

{'C': 0.01, 'penalty': 'l1', 'solver': 'liblinear'}

In [29]:
grid.best_score_

np.float64(0.8917142857142857)

In [ ]:
grid.predict(X_test)

array([1, 1, 1, ..., 0, 0, 0], shape=(3000,))

In [32]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [34]:
score = accuracy_score(y_test, grid.predict(X_test))
print(score)

0.895


In [38]:
confusion_mtrx = confusion_matrix(y_test, grid.predict(X_test))
print(confusion_mtrx)

[[1332  152]
 [ 163 1353]]
